DROP TABLE IF EXISTS scan_results CASCADE;
DROP TABLE IF EXISTS whois_records CASCADE;
DROP TABLE IF EXISTS dns_records CASCADE;
DROP TABLE IF EXISTS subdomains CASCADE;
DROP TABLE IF EXISTS scan_jobs CASCADE;
