name: CI/CD Pipeline

on:
  push:
    branches: [main, master, dev, homework-final]
  pull_request:
    branches: [main, master, dev]

jobs:
  # SỬA TÊN THÀNH Unit Tests CHO KHỚP RULE
  backend-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Run Backend Tests
        working-directory: ./homework-day1
        run: go test -v ./...

  # SỬA TÊN THÀNH Gosec Scanner CHO KHỚP RULE
  gosec-scan:
    name: Gosec Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Gosec Security Scan
        uses: securego/gosec@master
        with:
          args: ./homework-day1/...
        continue-on-error: true

  # SỬA TÊN THÀNH Gitleaks Scanner CHO KHỚP RULE
  gitleaks-scan:
    name: Gitleaks Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

    # Job quét lỗ hổng thư viện / dependencies
  trivy-scan:
    name: Trivy Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          severity: "HIGH,CRITICAL"
        continue-on-error: true

  # Job quét sâu lịch sử commit tìm secrets
  trufflehog-scan:
    name: TruffleHog Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: TruffleHog OSS Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ""
          head: HEAD
        continue-on-error: true
